<?php
if (!empty($_GET)) {
  $tz = $_GET['timezone']; 
  $place = "";
  switch ($tz)
  {
  case -12:
    $place = "Pacific/Kwajalein";
    break;
  case -11:
    $place = "Pacific/Samoa";
    break;
  case -10:
    $place = "Pacific/Honolulu";
    break;
  case -9:
    $place = "America/Juneau";
    break;    
  case -8:
    $place = "America/Los_Angeles";
    break;
  case -7:
    $place = "America/Denver";
    break;
  case -6:
    $place = "America/Mexico_City";
    break;
  case -5:
    $place = "America/Bogota";
    break;
  case -4:
    $place = "America/Caracas";
    break;
  case -3.5:
    $place = "America/St_Johns";
    break;
  case -3:
    $place = "America/Sao_Paulo";
    break;
  case -2:
    $place = "America/Barbados";
    break;
  case -1:
    $place = "Atlantic/Azores";
    break;
  case 0:
    $place = "Europe/London";
    break;
  case 1:
    $place = "Europe/Berlin";
    break;            
  case 2:
    $place = "Europe/Athens";
    break;
  case 3:
    $place = "Europe/Moscow";
    break;
  case 3.5:
    $place = "Asia/Tehran";
    break;    
  case 4:
    $place = "Asia/Tbilisi";
    break;
  case 4.5:
    $place = "Asia/Kabul";
    break;    
  case 5:
    $place = "Asia/Yekaterinburg";
    break;
  case 5.5:
    $place = "Asia/Calcutta";
    break;    
  case 6:
    $place = "Asia/Dhaka";
    break;
  case 7:
    $place = "Asia/Jakarta";
    break;
  case 8:
    $place = "Asia/Hong_Kong";
    break;
  case 9:
    $place = "Asia/Tokyo";
    break;
  case 9.5:
    $place = "Australia/Adelaide";
    break;    
  case 10:
    $place = "Australia/Sydney";
    break;            
  case 11:
    $place = "Asia/Magadan";
    break;          
  case 12:
    $place = "Pacific/Fiji";
    break;

  }
  //ToDo
  //better notification
  //select current timezone in select
  //remove _GET params
  //chek rest DST and non DST timezones?
  
  //NOTE in order for the sudo command below to run you need to add
  //this: www-data ALL=(ALL) NOPASSWD: ALL
  //to /etc/sudoers
  //not sure if it is the safest think to do :S
  exec('sudo ln -sf /usr/share/zoneinfo/'.$place.' /etc/localtime');
  print("Timezone set for: " . $place);
}  
?>

<div id="settings">
<hr>
	<h3><a href="#">Web Access</a></h3>
<hr>
	<table>
    <tr>
      <td colspan=2>Modify your username or password:</td>
    </tr>
    <tr>
      <td>Username:</td>
      <td><form><input type="text" id="username" /></td>
    </tr>
    <tr>
      <td>Password:</td>
      <td><input type="password" id="password" /></td>
    </tr>
    <tr>
      <td></td>
      <td align=right><input type="submit" value=" Change "></form></td>
    </tr>
  </table>
<hr>
	<h3><a href="#">Time Settings</a></h3>
<hr>
	 <table>
    <tr>
      <td>Local Time Zone:</td>
      <td>
        <select name="timezone" id="timezone">
              <option value="-12.0">(GMT -12:00) Eniwetok, Kwajalein</option>
              <option value="-11.0">(GMT -11:00) Midway Island, Samoa</option>
              <option value="-10.0">(GMT -10:00) Hawaii</option>
              <option value="-9.0">(GMT -9:00) Alaska</option>
              <option value="-8.0">(GMT -8:00) Pacific Time (US &amp; Canada)</option>
              <option value="-7.0">(GMT -7:00) Mountain Time (US &amp; Canada)</option>
              <option value="-6.0">(GMT -6:00) Central Time (US &amp; Canada), Mexico City</option>
              <option value="-5.0">(GMT -5:00) Eastern Time (US &amp; Canada), Bogota, Lima</option>
              <option value="-4.0">(GMT -4:00) Atlantic Time (Canada), Caracas, La Paz</option>
              <option value="-3.5">(GMT -3:30) Newfoundland</option>
              <option value="-3.0">(GMT -3:00) Brazil, Buenos Aires, Georgetown</option>
              <option value="-2.0">(GMT -2:00) Mid-Atlantic</option>
              <option value="-1.0">(GMT -1:00) Azores, Cape Verde Islands</option>
              <option value="0.0">(GMT) Western Europe Time, London, Lisbon</option>
              <option value="1.0">(GMT +1:00) Brussels, Copenhagen, Madrid, Paris</option>
              <option value="2.0" selected>(GMT +2:00) Athens, Cairo, South Africa</option>
              <option value="3.0">(GMT +3:00) Baghdad, Riyadh, Moscow, St. Petersburg</option>
              <option value="3.5">(GMT +3:30) Tehran</option>
              <option value="4.0">(GMT +4:00) Abu Dhabi, Muscat, Tbilisi</option>
              <option value="4.5">(GMT +4:30) Kabul</option>
              <option value="5.0">(GMT +5:00) Ekaterinburg, Islamabad</option>
              <option value="5.5">(GMT +5:30) Bombay, Calcutta, New Delhi</option>
              <option value="6.0">(GMT +6:00) Almaty, Dhaka, Colombo</option>
              <option value="7.0">(GMT +7:00) Bangkok, Hanoi, Jakarta</option>
              <option value="8.0">(GMT +8:00) Beijing, Singapore, Hong Kong</option>
              <option value="9.0">(GMT +9:00) Tokyo, Seoul, Osaka</option>
              <option value="9.5">(GMT +9:30) Adelaide, Darwin</option>
              <option value="10.0">(GMT +10:00) Eastern Australia</option>
              <option value="11.0">(GMT +11:00) Magadan, Solomon Islands, New Caledonia</option>
              <option value="12.0">(GMT +12:00) Auckland, Wellington, Fiji</option>
        </select>
      </td>
    </tr>
    <tr>
      <td>First day of week:</td>
      <td>
        <form>
        <input type="radio" name="firstday" value="sunday">&nbsp;Sunday &nbsp;&nbsp;
        <input type="radio" name="firstday" value="monday" checked="checked">&nbsp;Monday
      </td>
    </tr>
    <tr>
      <td></td>
      <td align=right><input type="submit" value=" Change "></form></td>
    </tr>
  </table>
<hr>
  <h3><a href="#">Temperature Settings:</a></h3>
<hr>
<table>
    <tr>
      <td>
        <form>
        <!--&deg;C-->
        <input type="radio" name="firstday" value="celsius" checked="checked">&nbsp;Celsius (&#8451;)&nbsp;&nbsp;
        <input type="radio" name="firstday" value="fahrenheit">&nbsp;Fahrenheit (&#8457;)&nbsp;&nbsp;
      </td>
      <td align=right><input type="submit" value=" Change "></form></td>
    </tr>
    
  </table>
<hr>
	<h3><a href="#">Network Settings:</a></h3>
<hr>
	Wired connection details:</br>
   <table>
    <tr>
      <td colspan=2>
        <form>
        <input type="radio" name="ipmethod" value="dhcp">&nbsp;Dynamic (DHCP) &nbsp;&nbsp;
        <input type="radio" name="ipmethod" value="static" checked="checked">&nbsp;Static
      </td>
    </tr>
    <tr>
      <td>
        IP Address:
      </td>
      <td>
        <input type="text" id="ip1" size="3" value="192" />.
        <input type="text" id="ip2" size="3" value="168" />.
        <input type="text" id="ip3" size="3" value="1" />.
        <input type="text" id="ip4" size="3" value="100" />
      </td>
    </tr>
    <tr>
      <td>
        Subnet Mask:
      </td>
      <td>
        <input type="text" id="mask1" size="3" value="255" />.
        <input type="text" id="mask2" size="3" value="255" />.
        <input type="text" id="mask3" size="3" value="255" />.
        <input type="text" id="mask4" size="3" value="0" />
      </td>
    </tr>
    <tr>
      <td>
        Default Gateway:
      </td>
      <td>
        <input type="text" id="gateway1" size="3" value="192" />.
        <input type="text" id="gateway2" size="3" value="168" />.
        <input type="text" id="gateway3" size="3" value="1" />.
        <input type="text" id="gateway4" size="3" value="1" />
      </td>
    </tr>
    <tr>
      <td>
        DNS:
      </td>
      <td>
        <input type="text" id="dns1" size="3" value="192" />.
        <input type="text" id="dns2" size="3" value="168" />.
        <input type="text" id="dns3" size="3" value="1" />.
        <input type="text" id="dns4" size="3" value="1" />
      </td>
    </tr>
    <tr>
      <td></td>
      <td align=right><input type="submit" value=" Change "></form></td>
    </tr>
  </table></br>
	Wireless connection details:
	<table>
    <tr>
      <td colspan=2>
        <form>
        <input type="radio" name="wirelessipmethod" value="dhcp">&nbsp;Dynamic (DHCP) &nbsp;&nbsp;
        <input type="radio" name="wirelessipmethod" value="static" checked="checked">&nbsp;Static
      </td>
    </tr>
    <tr>
      <td>
        IP Address:
      </td>
      <td>
        <input type="text" id="wirelessip1" size="3" value="192" />.
        <input type="text" id="wirelessip2" size="3" value="168" />.
        <input type="text" id="wirelessip3" size="3" value="1" />.
        <input type="text" id="wirelessip4" size="3" value="110" />
      </td>
    </tr>
    <tr>
      <td>
        Subnet Mask:
      </td>
      <td>
        <input type="text" id="wirelessmask1" size="3" value="255" />.
        <input type="text" id="wirelessmask2" size="3" value="255" />.
        <input type="text" id="wirelessmask3" size="3" value="255" />.
        <input type="text" id="wirelessmask4" size="3" value="0" />
      </td>
    </tr>
    <tr>
      <td>
        Default Gateway:
      </td>
      <td>
        <input type="text" id="wirelessgateway1" size="3" value="192" />.
        <input type="text" id="wirelessgateway2" size="3" value="168" />.
        <input type="text" id="wirelessgateway3" size="3" value="1" />.
        <input type="text" id="wirelessgateway4" size="3" value="1" />
      </td>
    </tr>
    <tr>
      <td>
        DNS:
      </td>
      <td>
        <input type="text" id="wirelessdns1" size="3" value="192" />.
        <input type="text" id="wirelessdns2" size="3" value="168" />.
        <input type="text" id="wirelessdns3" size="3" value="1" />.
        <input type="text" id="wirelessdns4" size="3" value="1" />
      </td>
    </tr>
    <tr>
      <td></td>
      <td align=right><input type="submit" value=" Change "></form></td>
    </tr>
  </table>
<hr>
	<h3><a href="#">Hestia Smart Settings:</a></h3>
<hr>
	<table>
    <tr>
      <td>Boiler Preheat Period:</td>
      <td>
        <select name="preheat" id="preheat">
              <option value="0">0</option>
              <option value="5">5</option>
              <option value="10">10</option>
              <option value="15">15</option>
              <option value="30" selected>30</option>
              <option value="45">45</option>
        </select>
        minutes &nbsp;&nbsp;
      </td>
      <td align=right><input type="submit" value=" Change "></form></td>
    </tr>
  </table>
<hr>
  <h3><a href="#">Extra Tools:</a></h3>
<hr>
  <table>
    <tr>
      <td>
        IR Learning Tool:
      </td>
    </tr>
    <tr>
      <td>
        Make Hestia learn your new IR remote
      </td>
    </tr>
    <tr>
      <td align=right>
        <input type="submit" value=" Start IR Tool ">
        </form>
      </td>
    </tr>
    <tr>
      <td>
        RF Pairing Tool:
      </td>
    </tr>
    <tr>
      <td>
        Pair a new RF module
      </td>
    </tr>
    <tr>
      <td align=right>
        <input type="submit" value=" Pair RF ">
        </form>
      </td>
    </tr>
  </table>
</div>
